echo "RPT_INFO:Input Ports  "

report_timing -from rid_s3       -path only -nosplit -net
report_timing -from rready_m1    -path only -nosplit -net
report_timing -from rlast_s7     -path only -nosplit -net
report_timing -from rlast_s6     -path only -nosplit -net
report_timing -from rlast_s5     -path only -nosplit -net
report_timing -from rlast_s4     -path only -nosplit -net
report_timing -from rlast_s3     -path only -nosplit -net
report_timing -from rlast_s2     -path only -nosplit -net
report_timing -from rlast_s1     -path only -nosplit -net
report_timing -from rid_s7       -path only -nosplit -net
report_timing -from rid_s6       -path only -nosplit -net
report_timing -from rid_s5       -path only -nosplit -net
report_timing -from rid_s4       -path only -nosplit -net
report_timing -from rresp_s1     -path only -nosplit -net
report_timing -from rid_s2       -path only -nosplit -net
report_timing -from rid_s1       -path only -nosplit -net
report_timing -from remap_n      -path only -nosplit -net
report_timing -from rdata_s7     -path only -nosplit -net
report_timing -from rdata_s6     -path only -nosplit -net
report_timing -from rdata_s5     -path only -nosplit -net
report_timing -from rdata_s4     -path only -nosplit -net
report_timing -from rdata_s3     -path only -nosplit -net
report_timing -from rdata_s2     -path only -nosplit -net
report_timing -from rdata_s1     -path only -nosplit -net
report_timing -from bvalid_s7    -path only -nosplit -net
report_timing -from bvalid_s6    -path only -nosplit -net
report_timing -from rvalid_s7    -path only -nosplit -net
report_timing -from wvalid_m1    -path only -nosplit -net
report_timing -from wstrb_m1     -path only -nosplit -net
report_timing -from wready_s7    -path only -nosplit -net
report_timing -from wready_s6    -path only -nosplit -net
report_timing -from wready_s5    -path only -nosplit -net
report_timing -from wready_s4    -path only -nosplit -net
report_timing -from wready_s3    -path only -nosplit -net
report_timing -from wready_s2    -path only -nosplit -net
report_timing -from wready_s1    -path only -nosplit -net
report_timing -from wlast_m1     -path only -nosplit -net
report_timing -from wid_m1       -path only -nosplit -net
report_timing -from wdata_m1     -path only -nosplit -net
report_timing -from bvalid_s5    -path only -nosplit -net
report_timing -from rvalid_s6    -path only -nosplit -net
report_timing -from rvalid_s5    -path only -nosplit -net
report_timing -from rvalid_s4    -path only -nosplit -net
report_timing -from rvalid_s3    -path only -nosplit -net
report_timing -from rvalid_s2    -path only -nosplit -net
report_timing -from rvalid_s1    -path only -nosplit -net
report_timing -from rresp_s7     -path only -nosplit -net
report_timing -from rresp_s6     -path only -nosplit -net
report_timing -from rresp_s5     -path only -nosplit -net
report_timing -from rresp_s4     -path only -nosplit -net
report_timing -from rresp_s3     -path only -nosplit -net
report_timing -from rresp_s2     -path only -nosplit -net
report_timing -from arready_s7   -path only -nosplit -net
report_timing -from awready_s3   -path only -nosplit -net
report_timing -from awready_s2   -path only -nosplit -net
report_timing -from awready_s1   -path only -nosplit -net
report_timing -from awprot_m1    -path only -nosplit -net
report_timing -from awlock_m1    -path only -nosplit -net
report_timing -from awlen_m1     -path only -nosplit -net
report_timing -from awid_m1      -path only -nosplit -net
report_timing -from awcache_m1   -path only -nosplit -net
report_timing -from awburst_m1   -path only -nosplit -net
report_timing -from awaddr_m1    -path only -nosplit -net
report_timing -from arvalid_m1   -path only -nosplit -net
report_timing -from arsize_m1    -path only -nosplit -net
report_timing -from awready_s4   -path only -nosplit -net
report_timing -from arready_s6   -path only -nosplit -net
report_timing -from arready_s5   -path only -nosplit -net
report_timing -from arready_s4   -path only -nosplit -net
report_timing -from arready_s3   -path only -nosplit -net
report_timing -from arready_s2   -path only -nosplit -net
report_timing -from arready_s1   -path only -nosplit -net
report_timing -from arprot_m1    -path only -nosplit -net
report_timing -from arlock_m1    -path only -nosplit -net
report_timing -from arlen_m1     -path only -nosplit -net
report_timing -from arid_m1      -path only -nosplit -net
report_timing -from arcache_m1   -path only -nosplit -net
report_timing -from arburst_m1   -path only -nosplit -net
report_timing -from bid_s7       -path only -nosplit -net
report_timing -from bvalid_s4    -path only -nosplit -net
report_timing -from bvalid_s3    -path only -nosplit -net
report_timing -from bvalid_s2    -path only -nosplit -net
report_timing -from bvalid_s1    -path only -nosplit -net
report_timing -from bresp_s7     -path only -nosplit -net
report_timing -from bresp_s6     -path only -nosplit -net
report_timing -from bresp_s5     -path only -nosplit -net
report_timing -from bresp_s4     -path only -nosplit -net
report_timing -from bresp_s3     -path only -nosplit -net
report_timing -from bresp_s2     -path only -nosplit -net
report_timing -from bresp_s1     -path only -nosplit -net
report_timing -from bready_m1    -path only -nosplit -net
report_timing -from araddr_m1    -path only -nosplit -net
report_timing -from bid_s6       -path only -nosplit -net
report_timing -from bid_s5       -path only -nosplit -net
report_timing -from bid_s4       -path only -nosplit -net
report_timing -from bid_s3       -path only -nosplit -net
report_timing -from bid_s2       -path only -nosplit -net
report_timing -from bid_s1       -path only -nosplit -net
report_timing -from awvalid_m1   -path only -nosplit -net
report_timing -from awsize_m1    -path only -nosplit -net
report_timing -from awready_s7   -path only -nosplit -net
report_timing -from awready_s6   -path only -nosplit -net
report_timing -from awready_s5   -path only -nosplit -net


echo "RPT_INFO:Output Ports  "

report_timing -to   dbg_awlock_s0 -path only  -nosplit -net
report_timing -to   dbg_arcache_s0 -path only  -nosplit -net
report_timing -to   dbg_arid_s0  -path only  -nosplit -net
report_timing -to   dbg_arlen_s0 -path only  -nosplit -net
report_timing -to   dbg_arlock_s0 -path only  -nosplit -net
report_timing -to   dbg_arprot_s0 -path only  -nosplit -net
report_timing -to   dbg_arready_s0 -path only  -nosplit -net
report_timing -to   dbg_arsize_s0 -path only  -nosplit -net
report_timing -to   dbg_arvalid_s0 -path only  -nosplit -net
report_timing -to   dbg_awaddr_s0 -path only  -nosplit -net
report_timing -to   dbg_awburst_s0 -path only  -nosplit -net
report_timing -to   dbg_awcache_s0 -path only  -nosplit -net
report_timing -to   dbg_awid_s0  -path only  -nosplit -net
report_timing -to   dbg_awlen_s0 -path only  -nosplit -net
report_timing -to   dbg_arburst_s0 -path only  -nosplit -net
report_timing -to   dbg_awprot_s0 -path only  -nosplit -net
report_timing -to   dbg_awready_s0 -path only  -nosplit -net
report_timing -to   dbg_awsize_s0 -path only  -nosplit -net
report_timing -to   dbg_awvalid_s0 -path only  -nosplit -net
report_timing -to   dbg_bid_s0   -path only  -nosplit -net
report_timing -to   dbg_bready_s0 -path only  -nosplit -net
report_timing -to   dbg_bresp_s0 -path only  -nosplit -net
report_timing -to   dbg_bvalid_s0 -path only  -nosplit -net
report_timing -to   dbg_rdata_s0 -path only  -nosplit -net
report_timing -to   dbg_rid_s0   -path only  -nosplit -net
report_timing -to   dbg_rlast_s0 -path only  -nosplit -net
report_timing -to   dbg_rready_s0 -path only  -nosplit -net
report_timing -to   dbg_rresp_s0 -path only  -nosplit -net
report_timing -to   awvalid_s5   -path only  -nosplit -net
report_timing -to   awprot_s7    -path only  -nosplit -net
report_timing -to   awready_m1   -path only  -nosplit -net
report_timing -to   awsize_s1    -path only  -nosplit -net
report_timing -to   awsize_s2    -path only  -nosplit -net
report_timing -to   awsize_s3    -path only  -nosplit -net
report_timing -to   awsize_s4    -path only  -nosplit -net
report_timing -to   awsize_s5    -path only  -nosplit -net
report_timing -to   awsize_s6    -path only  -nosplit -net
report_timing -to   awsize_s7    -path only  -nosplit -net
report_timing -to   awvalid_s1   -path only  -nosplit -net
report_timing -to   awvalid_s2   -path only  -nosplit -net
report_timing -to   awvalid_s3   -path only  -nosplit -net
report_timing -to   awvalid_s4   -path only  -nosplit -net
report_timing -to   dbg_rvalid_s0 -path only  -nosplit -net
report_timing -to   awvalid_s6   -path only  -nosplit -net
report_timing -to   awvalid_s7   -path only  -nosplit -net
report_timing -to   bid_m1       -path only  -nosplit -net
report_timing -to   bready_s1    -path only  -nosplit -net
report_timing -to   bready_s2    -path only  -nosplit -net
report_timing -to   bready_s3    -path only  -nosplit -net
report_timing -to   bready_s4    -path only  -nosplit -net
report_timing -to   bready_s5    -path only  -nosplit -net
report_timing -to   bready_s6    -path only  -nosplit -net
report_timing -to   bready_s7    -path only  -nosplit -net
report_timing -to   bresp_m1     -path only  -nosplit -net
report_timing -to   bvalid_m1    -path only  -nosplit -net
report_timing -to   dbg_araddr_s0 -path only  -nosplit -net
report_timing -to   wstrb_s1     -path only  -nosplit -net
report_timing -to   wid_s3       -path only  -nosplit -net
report_timing -to   wid_s4       -path only  -nosplit -net
report_timing -to   wid_s5       -path only  -nosplit -net
report_timing -to   wid_s6       -path only  -nosplit -net
report_timing -to   wid_s7       -path only  -nosplit -net
report_timing -to   wlast_s1     -path only  -nosplit -net
report_timing -to   wlast_s2     -path only  -nosplit -net
report_timing -to   wlast_s3     -path only  -nosplit -net
report_timing -to   wlast_s4     -path only  -nosplit -net
report_timing -to   wlast_s5     -path only  -nosplit -net
report_timing -to   wlast_s6     -path only  -nosplit -net
report_timing -to   wlast_s7     -path only  -nosplit -net
report_timing -to   wready_m1    -path only  -nosplit -net
report_timing -to   wid_s2       -path only  -nosplit -net
report_timing -to   wstrb_s2     -path only  -nosplit -net
report_timing -to   wstrb_s3     -path only  -nosplit -net
report_timing -to   wstrb_s4     -path only  -nosplit -net
report_timing -to   wstrb_s5     -path only  -nosplit -net
report_timing -to   wstrb_s6     -path only  -nosplit -net
report_timing -to   wstrb_s7     -path only  -nosplit -net
report_timing -to   wvalid_s1    -path only  -nosplit -net
report_timing -to   wvalid_s2    -path only  -nosplit -net
report_timing -to   wvalid_s3    -path only  -nosplit -net
report_timing -to   wvalid_s4    -path only  -nosplit -net
report_timing -to   wvalid_s5    -path only  -nosplit -net
report_timing -to   wvalid_s6    -path only  -nosplit -net
report_timing -to   wvalid_s7    -path only  -nosplit -net
report_timing -to   rready_s5    -path only  -nosplit -net
report_timing -to   dbg_wdata_s0 -path only  -nosplit -net
report_timing -to   dbg_wid_s0   -path only  -nosplit -net
report_timing -to   dbg_wlast_s0 -path only  -nosplit -net
report_timing -to   dbg_wready_s0 -path only  -nosplit -net
report_timing -to   dbg_wstrb_s0 -path only  -nosplit -net
report_timing -to   dbg_wvalid_s0 -path only  -nosplit -net
report_timing -to   rdata_m1     -path only  -nosplit -net
report_timing -to   rid_m1       -path only  -nosplit -net
report_timing -to   rlast_m1     -path only  -nosplit -net
report_timing -to   rready_s1    -path only  -nosplit -net
report_timing -to   rready_s2    -path only  -nosplit -net
report_timing -to   rready_s3    -path only  -nosplit -net
report_timing -to   rready_s4    -path only  -nosplit -net
report_timing -to   awprot_s6    -path only  -nosplit -net
report_timing -to   rready_s6    -path only  -nosplit -net
report_timing -to   rready_s7    -path only  -nosplit -net
report_timing -to   rresp_m1     -path only  -nosplit -net
report_timing -to   rvalid_m1    -path only  -nosplit -net
report_timing -to   wdata_s1     -path only  -nosplit -net
report_timing -to   wdata_s2     -path only  -nosplit -net
report_timing -to   wdata_s3     -path only  -nosplit -net
report_timing -to   wdata_s4     -path only  -nosplit -net
report_timing -to   wdata_s5     -path only  -nosplit -net
report_timing -to   wdata_s6     -path only  -nosplit -net
report_timing -to   wdata_s7     -path only  -nosplit -net
report_timing -to   wid_s1       -path only  -nosplit -net
report_timing -to   arprot_s1    -path only  -nosplit -net
report_timing -to   arlen_s2     -path only  -nosplit -net
report_timing -to   arlen_s3     -path only  -nosplit -net
report_timing -to   arlen_s4     -path only  -nosplit -net
report_timing -to   arlen_s5     -path only  -nosplit -net
report_timing -to   arlen_s6     -path only  -nosplit -net
report_timing -to   arlen_s7     -path only  -nosplit -net
report_timing -to   arlock_s1    -path only  -nosplit -net
report_timing -to   arlock_s2    -path only  -nosplit -net
report_timing -to   arlock_s3    -path only  -nosplit -net
report_timing -to   arlock_s4    -path only  -nosplit -net
report_timing -to   arlock_s5    -path only  -nosplit -net
report_timing -to   arlock_s6    -path only  -nosplit -net
report_timing -to   arlock_s7    -path only  -nosplit -net
report_timing -to   arlen_s1     -path only  -nosplit -net
report_timing -to   arprot_s2    -path only  -nosplit -net
report_timing -to   arprot_s3    -path only  -nosplit -net
report_timing -to   arprot_s4    -path only  -nosplit -net
report_timing -to   arprot_s5    -path only  -nosplit -net
report_timing -to   arprot_s6    -path only  -nosplit -net
report_timing -to   arprot_s7    -path only  -nosplit -net
report_timing -to   arready_m1   -path only  -nosplit -net
report_timing -to   arsize_s1    -path only  -nosplit -net
report_timing -to   arsize_s2    -path only  -nosplit -net
report_timing -to   arsize_s3    -path only  -nosplit -net
report_timing -to   arsize_s4    -path only  -nosplit -net
report_timing -to   arsize_s5    -path only  -nosplit -net
report_timing -to   arsize_s6    -path only  -nosplit -net
report_timing -to   arcache_s1   -path only  -nosplit -net
report_timing -to   araddr_s2    -path only  -nosplit -net
report_timing -to   araddr_s3    -path only  -nosplit -net
report_timing -to   araddr_s4    -path only  -nosplit -net
report_timing -to   araddr_s5    -path only  -nosplit -net
report_timing -to   araddr_s6    -path only  -nosplit -net
report_timing -to   araddr_s7    -path only  -nosplit -net
report_timing -to   arburst_s1   -path only  -nosplit -net
report_timing -to   arburst_s2   -path only  -nosplit -net
report_timing -to   arburst_s3   -path only  -nosplit -net
report_timing -to   arburst_s4   -path only  -nosplit -net
report_timing -to   arburst_s5   -path only  -nosplit -net
report_timing -to   arburst_s6   -path only  -nosplit -net
report_timing -to   arburst_s7   -path only  -nosplit -net
report_timing -to   arsize_s7    -path only  -nosplit -net
report_timing -to   arcache_s2   -path only  -nosplit -net
report_timing -to   arcache_s3   -path only  -nosplit -net
report_timing -to   arcache_s4   -path only  -nosplit -net
report_timing -to   arcache_s5   -path only  -nosplit -net
report_timing -to   arcache_s6   -path only  -nosplit -net
report_timing -to   arcache_s7   -path only  -nosplit -net
report_timing -to   arid_s1      -path only  -nosplit -net
report_timing -to   arid_s2      -path only  -nosplit -net
report_timing -to   arid_s3      -path only  -nosplit -net
report_timing -to   arid_s4      -path only  -nosplit -net
report_timing -to   arid_s5      -path only  -nosplit -net
report_timing -to   arid_s6      -path only  -nosplit -net
report_timing -to   arid_s7      -path only  -nosplit -net
report_timing -to   awlen_s6     -path only  -nosplit -net
report_timing -to   awcache_s7   -path only  -nosplit -net
report_timing -to   awid_s1      -path only  -nosplit -net
report_timing -to   awid_s2      -path only  -nosplit -net
report_timing -to   awid_s3      -path only  -nosplit -net
report_timing -to   awid_s4      -path only  -nosplit -net
report_timing -to   awid_s5      -path only  -nosplit -net
report_timing -to   awid_s6      -path only  -nosplit -net
report_timing -to   awid_s7      -path only  -nosplit -net
report_timing -to   awlen_s1     -path only  -nosplit -net
report_timing -to   awlen_s2     -path only  -nosplit -net
report_timing -to   awlen_s3     -path only  -nosplit -net
report_timing -to   awlen_s4     -path only  -nosplit -net
report_timing -to   awlen_s5     -path only  -nosplit -net
report_timing -to   awcache_s6   -path only  -nosplit -net
report_timing -to   awlen_s7     -path only  -nosplit -net
report_timing -to   awlock_s1    -path only  -nosplit -net
report_timing -to   awlock_s2    -path only  -nosplit -net
report_timing -to   awlock_s3    -path only  -nosplit -net
report_timing -to   awlock_s4    -path only  -nosplit -net
report_timing -to   awlock_s5    -path only  -nosplit -net
report_timing -to   awlock_s6    -path only  -nosplit -net
report_timing -to   awlock_s7    -path only  -nosplit -net
report_timing -to   awprot_s1    -path only  -nosplit -net
report_timing -to   awprot_s2    -path only  -nosplit -net
report_timing -to   awprot_s3    -path only  -nosplit -net
report_timing -to   awprot_s4    -path only  -nosplit -net
report_timing -to   awprot_s5    -path only  -nosplit -net
report_timing -to   awaddr_s7    -path only  -nosplit -net
report_timing -to   arvalid_s1   -path only  -nosplit -net
report_timing -to   arvalid_s2   -path only  -nosplit -net
report_timing -to   arvalid_s3   -path only  -nosplit -net
report_timing -to   arvalid_s4   -path only  -nosplit -net
report_timing -to   arvalid_s5   -path only  -nosplit -net
report_timing -to   arvalid_s6   -path only  -nosplit -net
report_timing -to   arvalid_s7   -path only  -nosplit -net
report_timing -to   awaddr_s1    -path only  -nosplit -net
report_timing -to   awaddr_s2    -path only  -nosplit -net
report_timing -to   awaddr_s3    -path only  -nosplit -net
report_timing -to   awaddr_s4    -path only  -nosplit -net
report_timing -to   awaddr_s5    -path only  -nosplit -net
report_timing -to   awaddr_s6    -path only  -nosplit -net
report_timing -to   araddr_s1    -path only  -nosplit -net
report_timing -to   awburst_s1   -path only  -nosplit -net
report_timing -to   awburst_s2   -path only  -nosplit -net
report_timing -to   awburst_s3   -path only  -nosplit -net
report_timing -to   awburst_s4   -path only  -nosplit -net
report_timing -to   awburst_s5   -path only  -nosplit -net
report_timing -to   awburst_s6   -path only  -nosplit -net
report_timing -to   awburst_s7   -path only  -nosplit -net
report_timing -to   awcache_s1   -path only  -nosplit -net
report_timing -to   awcache_s2   -path only  -nosplit -net
report_timing -to   awcache_s3   -path only  -nosplit -net
report_timing -to   awcache_s4   -path only  -nosplit -net
report_timing -to   awcache_s5   -path only  -nosplit -net


