
   `undef GS_AW
   `undef GS_DW
   `undef GS_WW
   `undef GS_ID
   `undef GS_BW
   `undef GS_LOWPWR_HS_IF
   `undef GS_LOWPWR_NOPX_CNT
   `undef GS_LOWPWR_NOPX_CNT_W
   `undef GS_LOWPWR_LEGACY_IF
   `undef GS_AXI_EX_ACCESS
   `undef GS_GIF_LITE
   `undef GS_BID_BUFFER
   `undef GS_RID_BUFFER
   `undef GS_DIRECT_GIF_READY
   `undef GS_REQ_BUFFER
   `undef GS_LOWPWR_PENDTRANS_MAX
   `undef GS_LOWPWR_PENDTRANS_CNT_W
   `undef GS_WDATA_BUFFER
   `undef GS_DIRECT_AXI_READY
   `undef GS_RESP_BUFFER
   `undef SIM_ACLK_PERIOD
   `undef SIM_GCLK_PERIOD
   `undef GS_SRESP_OK_R
   `undef GS_SRESP_OK_W
   `undef GS_SRESP_SLVERR_R
   `undef GS_SRESP_SLVERR_W
   `undef GS_BURST_FIXED
   `undef GS_BURST_INCR
   `undef GS_BURST_WRAP
   `undef GS_BURST_UINCR
   `undef GS_AXI_FIXED
   `undef GS_AXI_INCR
   `undef GS_AXI_WRAP
   `undef GS_AXI_RESVD
   `undef GS_AXI_OKAY
   `undef GS_AXI_EXOKAY
   `undef GS_AXI_SLVERR
   `undef GS_AXI_DECERR
   `undef RM_BCM01
   `undef RM_BCM02
   `undef RM_BCM03
   `undef RM_BCM05
   `undef RM_BCM06
   `undef RM_BCM07
   `undef RM_BCM08
   `undef RM_BCM09
   `undef RM_BCM10
   `undef RM_BCM11
   `undef RM_BCM12
   `undef RM_BCM15
   `undef RM_BCM16
   `undef RM_BCM21
   `undef RM_BCM22
   `undef RM_BCM23
   `undef RM_BCM24
   `undef RM_BCM25
   `undef RM_BCM26
   `undef RM_BCM27
   `undef RM_BCM28
   `undef RM_BCM29
   `undef RM_BCM30
   `undef RM_BCM31
   `undef RM_BCM32
   `undef RM_BCM43
   `undef RM_BCM44
   `undef RM_BCM46_A
   `undef RM_BCM46_B
   `undef RM_BCM46_C
   `undef RM_BCM46_D
   `undef RM_BCM47
   `undef RM_BCM51
   `undef RM_BCM52
   `undef RM_BCM53
   `undef RM_BCM54
   `undef RM_BCM55
   `undef RM_BCM57
   `undef RM_BCM58
   `undef RM_BCM59
   `undef RM_BCM64
   `undef RM_BCM65
   `undef RM_BCM66
   `undef RM_BCM71
   `undef RM_BCM72
   `undef RM_BCM73
   `undef RM_BCM76
   `undef GS_BW_MAX

