
   `undef USE_FOUNDATION
   `undef X2X_HAS_INC_DEBUG_LOGIC
   `undef X2X_TB_DEBUG_LEVEL
   `undef USE_PARAM_VARS_PROC
   `undef PARAM_VARS_PROC
   `undef X2X_USE_RANDOM_SEED
   `undef X2X_SEED
   `undef X2X_PARAM_LOCKDOWN
   `undef X2X_CH_SEL
   `undef X2X_MP_DW
   `undef X2X_MP_SW
   `undef X2X_MP_AW
   `undef X2X_MP_IDW
   `undef X2X_MP_BLW
   `undef X2X_SP_DW
   `undef X2X_SP_SW
   `undef X2X_SP_AW
   `undef X2X_SP_IDW
   `undef X2X_SP_BLW
   `undef X2X_HAS_ET
   `undef X2X_AW_BUF_DEPTH
   `undef X2X_AR_BUF_DEPTH
   `undef X2X_W_BUF_DEPTH
   `undef X2X_B_BUF_DEPTH
   `undef X2X_R_BUF_DEPTH
   `undef X2X_CLK_MODE
   `undef X2X_MP_SYNC_DEPTH
   `undef X2X_SP_SYNC_DEPTH
   `undef X2X_LOWPWR_HS_IF
   `undef X2X_LOWPWR_NOPX_CNT
   `undef X2X_LOWPWR_NOPX_CNT_LOG2
   `undef X2X_LOWPWR_NOPX_CNT_P1_LOG2
   `undef X2X_MAX_URIDA
   `undef X2X_LOG2_MAX_URIDA
   `undef X2X_MAX_UWIDA
   `undef X2X_MAX_RCA_ID
   `undef X2X_MAX_WCA_ID
   `undef X2X_WID
   `undef X2X_LOG2_WID
   `undef X2X_HAS_WI_FAN_OUT
   `undef X2X_WIP_BYPASS
   `undef X2X_HAS_TX_UPSIZE
   `undef X2X_UPSIZE_ANY_ASIZE
   `undef X2X_HAS_LOCKING
   `undef X2X_HAS_WRAP_BURST
   `undef X2X_WRAP_BURST
   `undef X2X_HAS_PIPELINE
   `undef X2X_HAS_TZ_SUPPORT
   `undef X2X_MAX_SBW
   `undef X2X_HAS_AWSB
   `undef X2X_AW_SBW
   `undef X2X_HAS_WSB
   `undef X2X_W_SBW
   `undef X2X_HAS_BSB
   `undef X2X_B_SBW
   `undef X2X_HAS_ARSB
   `undef X2X_AR_SBW
   `undef X2X_HAS_RSB
   `undef X2X_R_SBW
   `undef X2X_RD_CHANNELS
   `undef X2X_NUM_W_PORTS
   `undef X2X_LOG2_NUM_W_PORTS
   `undef X2X_INTERNAL_AW
   `undef X2X_DUAL_CLK
   `undef X2X_MAX_MP_ALEN
   `undef X2X_MAX_SP_ALEN
   `undef X2X_MAX_MP_BYTES
   `undef X2X_MAX_SP_BYTES
   `undef X2X_LOG2_MAX_MP_BYTES
   `undef X2X_0LOG2_MAX_MP_BYTES
   `undef X2X_LOG2_MAX_SP_BYTES
   `undef X2X_0LOG2_MAX_SP_BYTES
   `undef X2X_MAX_MP_ASIZE
   `undef X2X_MAX_SP_ASIZE
   `undef X2X_MAX_MP_TOTAL_BYTE
   `undef X2X_MAX_SP_TOTAL_BYTE
   `undef X2X_LOG2_MP_BYTE
   `undef X2X_LOG2_SP_BYTE
   `undef X2X_WIP_FIFO_D
   `undef X2X_LOG2_WIP_FIFO_D
   `undef X2X_INTERNAL_BW
   `undef X2X_LOG2_MAX_WCA_ID
   `undef X2X_MAX_WCA_ID_P1L2
   `undef X2X_LOG2_MAX_RCA_ID
   `undef X2X_MAX_RCA_ID_P1L2
   `undef X2X_AW_BUF_DEPTH_L2
   `undef X2X_AW_BUF_DEPTH_P1L2
   `undef X2X_W_BUF_DEPTH_L2
   `undef X2X_W_BUF_DEPTH_P1L2
   `undef X2X_B_BUF_DEPTH_L2
   `undef X2X_B_BUF_DEPTH_P1L2
   `undef X2X_AR_BUF_DEPTH_L2
   `undef X2X_AR_BUF_DEPTH_P1L2
   `undef X2X_R_BUF_DEPTH_L2
   `undef X2X_R_BUF_DEPTH_P1L2
   `undef X2X_LOG2_MP_SW
   `undef X2X_LOG2_SP_SW
   `undef X2X_ADDR_TRK_W
   `undef X2X_TX_ALTER
   `undef X2X_HAS_TX_NO_ALTER
   `undef X2X_SP_W_BEATS_PER_POP_W
   `undef X2X_SP_W_RSFIFO_W
   `undef X2X_SP_W_RSFIFO_D
   `undef X2X_SP_W_RSFIFO_D_L2
   `undef X2X_SP_W_RSFIFO_D_P1L2
   `undef X2X_DATA_SEL_W
   `undef X2X_W_LP_REG_DEPTH_L2
   `undef X2X_R_LP_REG_DEPTH_L2
   `undef X2X_W_LP_REG_DEPTH_PDL2
   `undef X2X_R_LP_REG_DEPTH_PDL2
   `undef X2X_RS_RATIO
   `undef X2X_SP_MP_DW_SAME
   `undef X2X_MPDW128
   `undef X2X_SPDW128
   `undef X2X_MPDW_GRTR_OR_EQ_16
   `undef X2X_MPDW_GRTR_OR_EQ_32
   `undef X2X_MPDW_GRTR_OR_EQ_64
   `undef X2X_MPDW_GRTR_OR_EQ_128
   `undef X2X_AW_MP_LRGR_OR_SAME
   `undef X2X_IDW_MP_LRGR_OR_SAME
   `undef X2X_ARPYLD_PROT_RHS_MP
   `undef X2X_ARPYLD_PROT_LHS_MP
   `undef X2X_ARPYLD_PROT_MP
   `undef X2X_ARPYLD_CACHE_RHS_MP
   `undef X2X_ARPYLD_CACHE_LHS_MP
   `undef X2X_ARPYLD_CACHE_MP
   `undef X2X_ARPYLD_LOCK_RHS_MP
   `undef X2X_ARPYLD_LOCK_LHS_MP
   `undef X2X_ARPYLD_LOCK_MP
   `undef X2X_ARPYLD_BURST_RHS_MP
   `undef X2X_ARPYLD_BURST_LHS_MP
   `undef X2X_ARPYLD_BURST_MP
   `undef X2X_ARPYLD_SIZE_RHS_MP
   `undef X2X_ARPYLD_SIZE_LHS_MP
   `undef X2X_ARPYLD_SIZE_MP
   `undef X2X_ARPYLD_LEN_RHS_MP
   `undef X2X_ARPYLD_LEN_LHS_MP
   `undef X2X_ARPYLD_LEN_MP
   `undef X2X_ARPYLD_ADDR_RHS_MP
   `undef X2X_ARPYLD_ADDR_LHS_MP
   `undef X2X_ARPYLD_ADDR_MP
   `undef X2X_ARPYLD_ID_RHS_MP
   `undef X2X_ARPYLD_ID_LHS_MP
   `undef X2X_ARPYLD_ID_MP
   `undef X2X_ARPYLD_W_MP
   `undef X2X_RPYLD_LAST_LHS_MP
   `undef X2X_RPYLD_LAST_MP
   `undef X2X_RPYLD_RESP_RHS_MP
   `undef X2X_RPYLD_RESP_LHS_MP
   `undef X2X_RPYLD_RESP_MP
   `undef X2X_RPYLD_DATA_RHS_MP
   `undef X2X_RPYLD_DATA_LHS_MP
   `undef X2X_RPYLD_DATA_MP
   `undef X2X_RPYLD_ID_RHS_MP
   `undef X2X_RPYLD_ID_LHS_MP
   `undef X2X_RPYLD_ID_MP
   `undef X2X_RPYLD_W_MP
   `undef X2X_AWPYLD_PROT_RHS_MP
   `undef X2X_AWPYLD_PROT_LHS_MP
   `undef X2X_AWPYLD_PROT_MP
   `undef X2X_AWPYLD_CACHE_RHS_MP
   `undef X2X_AWPYLD_CACHE_LHS_MP
   `undef X2X_AWPYLD_CACHE_MP
   `undef X2X_AWPYLD_LOCK_RHS_MP
   `undef X2X_AWPYLD_LOCK_LHS_MP
   `undef X2X_AWPYLD_LOCK_MP
   `undef X2X_AWPYLD_BURST_RHS_MP
   `undef X2X_AWPYLD_BURST_LHS_MP
   `undef X2X_AWPYLD_BURST_MP
   `undef X2X_AWPYLD_SIZE_RHS_MP
   `undef X2X_AWPYLD_SIZE_LHS_MP
   `undef X2X_AWPYLD_SIZE_MP
   `undef X2X_AWPYLD_LEN_RHS_MP
   `undef X2X_AWPYLD_LEN_LHS_MP
   `undef X2X_AWPYLD_LEN_MP
   `undef X2X_AWPYLD_ADDR_RHS_MP
   `undef X2X_AWPYLD_ADDR_LHS_MP
   `undef X2X_AWPYLD_ADDR_MP
   `undef X2X_AWPYLD_ID_RHS_MP
   `undef X2X_AWPYLD_ID_LHS_MP
   `undef X2X_AWPYLD_ID_MP
   `undef X2X_AWPYLD_W_MP
   `undef X2X_WPYLD_LAST_LHS_MP
   `undef X2X_WPYLD_LAST_MP
   `undef X2X_WPYLD_STRB_RHS_MP
   `undef X2X_WPYLD_STRB_LHS_MP
   `undef X2X_WPYLD_STRB_MP
   `undef X2X_WPYLD_DATA_RHS_MP
   `undef X2X_WPYLD_DATA_LHS_MP
   `undef X2X_WPYLD_DATA_MP
   `undef X2X_WPYLD_ID_RHS_MP
   `undef X2X_WPYLD_ID_LHS_MP
   `undef X2X_WPYLD_ID_MP
   `undef X2X_WPYLD_W_MP
   `undef X2X_BPYLD_RESP_RHS_MP
   `undef X2X_BPYLD_RESP_LHS_MP
   `undef X2X_BPYLD_RESP_MP
   `undef X2X_BPYLD_ID_RHS_MP
   `undef X2X_BPYLD_ID_LHS_MP
   `undef X2X_BPYLD_ID_MP
   `undef X2X_BPYLD_W_MP
   `undef X2X_ARPYLD_PROT_RHS_SP
   `undef X2X_ARPYLD_PROT_LHS_SP
   `undef X2X_ARPYLD_PROT_SP
   `undef X2X_ARPYLD_CACHE_RHS_SP
   `undef X2X_ARPYLD_CACHE_LHS_SP
   `undef X2X_ARPYLD_CACHE_SP
   `undef X2X_ARPYLD_LOCK_RHS_SP
   `undef X2X_ARPYLD_LOCK_LHS_SP
   `undef X2X_ARPYLD_LOCK_SP
   `undef X2X_ARPYLD_BURST_RHS_SP
   `undef X2X_ARPYLD_BURST_LHS_SP
   `undef X2X_ARPYLD_BURST_SP
   `undef X2X_ARPYLD_SIZE_RHS_SP
   `undef X2X_ARPYLD_SIZE_LHS_SP
   `undef X2X_ARPYLD_SIZE_SP
   `undef X2X_ARPYLD_LEN_RHS_SP
   `undef X2X_ARPYLD_LEN_LHS_SP
   `undef X2X_ARPYLD_LEN_SP
   `undef X2X_ARPYLD_ADDR_RHS_SP
   `undef X2X_ARPYLD_ADDR_LHS_SP
   `undef X2X_ARPYLD_ADDR_SP
   `undef X2X_ARPYLD_ID_RHS_SP
   `undef X2X_ARPYLD_ID_LHS_SP
   `undef X2X_ARPYLD_ID_SP
   `undef X2X_ARPYLD_W_SP
   `undef X2X_RPYLD_LAST_LHS_SP
   `undef X2X_RPYLD_LAST_SP
   `undef X2X_RPYLD_RESP_RHS_SP
   `undef X2X_RPYLD_RESP_LHS_SP
   `undef X2X_RPYLD_RESP_SP
   `undef X2X_RPYLD_DATA_RHS_SP
   `undef X2X_RPYLD_DATA_LHS_SP
   `undef X2X_RPYLD_DATA_SP
   `undef X2X_RPYLD_ID_RHS_SP
   `undef X2X_RPYLD_ID_LHS_SP
   `undef X2X_RPYLD_ID_SP
   `undef X2X_RPYLD_W_SP
   `undef X2X_AWPYLD_PROT_RHS_SP
   `undef X2X_AWPYLD_PROT_LHS_SP
   `undef X2X_AWPYLD_PROT_SP
   `undef X2X_AWPYLD_CACHE_RHS_SP
   `undef X2X_AWPYLD_CACHE_LHS_SP
   `undef X2X_AWPYLD_CACHE_SP
   `undef X2X_AWPYLD_LOCK_RHS_SP
   `undef X2X_AWPYLD_LOCK_LHS_SP
   `undef X2X_AWPYLD_LOCK_SP
   `undef X2X_AWPYLD_BURST_RHS_SP
   `undef X2X_AWPYLD_BURST_LHS_SP
   `undef X2X_AWPYLD_BURST_SP
   `undef X2X_AWPYLD_SIZE_RHS_SP
   `undef X2X_AWPYLD_SIZE_LHS_SP
   `undef X2X_AWPYLD_SIZE_SP
   `undef X2X_AWPYLD_LEN_RHS_SP
   `undef X2X_AWPYLD_LEN_LHS_SP
   `undef X2X_AWPYLD_LEN_SP
   `undef X2X_AWPYLD_ADDR_RHS_SP
   `undef X2X_AWPYLD_ADDR_LHS_SP
   `undef X2X_AWPYLD_ADDR_SP
   `undef X2X_AWPYLD_ID_RHS_SP
   `undef X2X_AWPYLD_ID_LHS_SP
   `undef X2X_AWPYLD_ID_SP
   `undef X2X_AWPYLD_W_SP
   `undef X2X_WPYLD_LAST_LHS_SP
   `undef X2X_WPYLD_LAST_SP
   `undef X2X_WPYLD_STRB_RHS_SP
   `undef X2X_WPYLD_STRB_LHS_SP
   `undef X2X_WPYLD_STRB_SP
   `undef X2X_WPYLD_DATA_RHS_SP
   `undef X2X_WPYLD_DATA_LHS_SP
   `undef X2X_WPYLD_DATA_SP
   `undef X2X_WPYLD_ID_RHS_SP
   `undef X2X_WPYLD_ID_LHS_SP
   `undef X2X_WPYLD_ID_SP
   `undef X2X_WPYLD_W_SP
   `undef X2X_BPYLD_RESP_RHS_SP
   `undef X2X_BPYLD_RESP_LHS_SP
   `undef X2X_BPYLD_RESP_SP
   `undef X2X_BPYLD_ID_RHS_SP
   `undef X2X_BPYLD_ID_LHS_SP
   `undef X2X_BPYLD_ID_SP
   `undef X2X_BPYLD_W_SP
   `undef X2X_AW_CH_FIFO_W
   `undef X2X_N_TESTCASE_DUPLICATION
   `undef X2X_MAX_DW
   `undef X2X_MAX_SW
   `undef X2X_LOG2_MAX_SW
   `undef X2X_BSW
   `undef X2X_BTW
   `undef X2X_LTW
   `undef X2X_CTW
   `undef X2X_PTW
   `undef X2X_BRW
   `undef X2X_RRW
   `undef X2X_LT_NORM
   `undef X2X_LT_EX
   `undef X2X_LT_LOCK
   `undef X2X_PT_PRVLGD
   `undef X2X_PT_NORM
   `undef X2X_PT_SECURE
   `undef X2X_PT_NSECURE
   `undef X2X_PT_INSTRUCT
   `undef X2X_PT_DATA
   `undef X2X_PT_PRVLGD_BIT
   `undef X2X_PT_SECURE_BIT
   `undef X2X_PT_INSTRUCT_BIT
   `undef X2X_RESP_OKAY
   `undef X2X_RESP_EXOKAY
   `undef X2X_RESP_SLVERR
   `undef X2X_RESP_DECERR
   `undef X2X_BT_FIXED
   `undef X2X_BT_INCR
   `undef X2X_BT_WRAP
   `undef X2X_BT_X
   `undef X2X_NOREQ_LOCKING
   `undef X2X_REQ_LOCKING
   `undef X2X_W_CH
   `undef X2X_NOT_W_CH
   `undef X2X_AW_CH
   `undef X2X_NOT_AW_CH
   `undef X2X_R_CH
   `undef X2X_NOT_R_CH
   `undef X2X_ADDR_CH
   `undef X2X_NOT_ADDR_CH
   `undef X2X_TX_NO_ALTER
   `undef X2X_LEN_ONLY_ALTER
   `undef X2X_MP_LRGR_ALTER
   `undef X2X_SP_LRGR_ALTER
   `undef X2X_SP_LRGR_US_ALTER
   `undef NORMAL
   `undef EXCLUS
   `undef LOCKED
   `undef NO_ACTION
   `undef AS_IS_OR_US_INLAST
   `undef MUL_XACT_OR_US_INLAST
   `undef MUL_XACT_OR_US_NOTLAST
   `undef SINGLE_XACT_INLAST
   `undef MUL_XACT_INLAST
   `undef MUL_XACT_NOTLAST
   `undef IDLE_CTRL
   `undef MUX_OVERONE
   `undef MUX_WRAP_BOUND
   `undef MUX_WRAP
   `undef MUX_CROSS
   `undef MUX_FI_MUL
   `undef MUX_FI_LAST
   `undef MXI_WRAP
   `undef MXI_FI
   `undef MXUI_SINGLE
   `undef MXUI_NO_CROSS
   `undef MXUI_CROSS
   `undef MXUI_DS
   `undef MXUI_FI_SINGLE
   `undef MXUI_FI_MUL
   `undef MXUI_FI_DS
   `undef RM_BCM01
   `undef RM_BCM02
   `undef RM_BCM03
   `undef RM_BCM05
   `undef RM_BCM06
   `undef RM_BCM07
   `undef RM_BCM08
   `undef RM_BCM09
   `undef RM_BCM10
   `undef RM_BCM11
   `undef RM_BCM12
   `undef RM_BCM15
   `undef RM_BCM16
   `undef RM_BCM21
   `undef RM_BCM22
   `undef RM_BCM23
   `undef RM_BCM24
   `undef RM_BCM25
   `undef RM_BCM26
   `undef RM_BCM27
   `undef RM_BCM28
   `undef RM_BCM29
   `undef RM_BCM30
   `undef RM_BCM31
   `undef RM_BCM32
   `undef RM_BCM43
   `undef RM_BCM44
   `undef RM_BCM46_A
   `undef RM_BCM46_B
   `undef RM_BCM46_C
   `undef RM_BCM46_D
   `undef RM_BCM47
   `undef RM_BCM51
   `undef RM_BCM52
   `undef RM_BCM53
   `undef RM_BCM54
   `undef RM_BCM55
   `undef RM_BCM57
   `undef RM_BCM58
   `undef RM_BCM59
   `undef RM_BCM64
   `undef RM_BCM65
   `undef RM_BCM66
   `undef RM_BCM71
   `undef RM_BCM72
   `undef RM_BCM73
   `undef RM_BCM76
   `undef BUS_AWPYLD_W_SP
   `undef BUS_WPYLD_W_MP
   `undef BUS_WPYLD_W_SP
   `undef BUS_BPYLD_W_SP

