
   `undef GM_AW
   `undef GM_DW
   `undef GM_ID
   `undef GM_BW
   `undef GM_LOWPWR_HS_IF
   `undef GM_LOWPWR_NOPX_CNT
   `undef GM_LOWPWR_NOPX_CNT_W
   `undef GM_LOWPWR_LEGACY_IF
   `undef GM_MAX_PENDTRANS_READ
   `undef GM_MAX_PENDTRANS_WRITE
   `undef GM_CNT_PENDTRANS_READ_W
   `undef GM_CNT_PENDTRANS_WRITE_W
   `undef GM_WW
   `undef GM_DIRECT_AXI_READY
   `undef GM_REQ_BUFFER
   `undef GM_REQ_BUFFER_AW
   `undef GM_WDATA_BUFFER
   `undef GM_WDATA_BUFFER_AW
   `undef GM_DIRECT_GIF_READY
   `undef GM_RESP_BUFFER
   `undef GM_RESP_BUFFER_AW
   `undef GM_BLOCK_READ
   `undef GM_BLOCK_WRITE
   `undef SIM_ACLK_PERIOD
   `undef SIM_GCLK_PERIOD
   `undef RM_BCM01
   `undef RM_BCM02
   `undef RM_BCM03
   `undef RM_BCM05
   `undef RM_BCM06
   `undef RM_BCM07
   `undef RM_BCM08
   `undef RM_BCM09
   `undef RM_BCM10
   `undef RM_BCM11
   `undef RM_BCM12
   `undef RM_BCM15
   `undef RM_BCM16
   `undef RM_BCM21
   `undef RM_BCM22
   `undef RM_BCM23
   `undef RM_BCM24
   `undef RM_BCM25
   `undef RM_BCM26
   `undef RM_BCM27
   `undef RM_BCM28
   `undef RM_BCM29
   `undef RM_BCM30
   `undef RM_BCM31
   `undef RM_BCM32
   `undef RM_BCM43
   `undef RM_BCM44
   `undef RM_BCM46_A
   `undef RM_BCM46_B
   `undef RM_BCM46_C
   `undef RM_BCM46_D
   `undef RM_BCM47
   `undef RM_BCM51
   `undef RM_BCM52
   `undef RM_BCM53
   `undef RM_BCM54
   `undef RM_BCM55
   `undef RM_BCM57
   `undef RM_BCM58
   `undef RM_BCM59
   `undef RM_BCM64
   `undef RM_BCM65
   `undef RM_BCM66
   `undef RM_BCM71
   `undef RM_BCM72
   `undef RM_BCM73
   `undef RM_BCM76

